#ifndef TT_INTERFACE_H
#define TT_INTERFACE_H

#include "cdef.h"
#include "SHMEM_Layout.h"

// Define if FGC only (1) 
// or FAC together with FAC and CAN Restbus simulation should be used (0)
#define TT_FGC_ONLY     1

typedef enum
{
   TT_NextStepLegacy                            = SHMEM_nenTrace_NextStepLegacy,
   TT_NextStepHmi                               = SHMEM_nenTrace_NextStepHmi,
   TT_KeyPress                                  = SHMEM_nenTrace_KeyPress,
   TT_KeyRelease                                = SHMEM_nenTrace_KeyRelease,
   TT_APIM_vTriggerStateChange                  = SHMEM_nenTrace_APIM_vTriggerStateChange,
   TT_vToggleAPIMStateChange                    = SHMEM_nenTrace_vToggleAPIMStateChange,
   TT_boIsCriticalState                         = SHMEM_nenTrace_boIsCriticalState,
   TT_Error_WAS_Exc_MessageQueuePanic           = SHMEM_nenTrace_Error_WAS_Exc_MessageQueuePanic,
   TT_Error_WAS_Exc_MessageQueueFull            = SHMEM_nenTrace_Error_WAS_Exc_MessageQueueFull,
   TT_SetPanicMode                              = SHMEM_nenTrace_SetPanicMode,
   TT_SetHMIKl15                                = SHMEM_nenTrace_SetHMIKl15,
   TT_SwitchKl15                                = SHMEM_nenTrace_SwitchKl15,
   TT_ExecFunction                              = SHMEM_nenTrace_ExecFunction,
   TT_SendEvent                                 = SHMEM_nenTrace_SendEvent,
   TT_EPFMI_vMmiKeyCallback                     = SHMEM_nenTrace_EPFMI_vMmiKeyCallback,
   TT_EPFMI_vMmiDoAction                        = SHMEM_nenTrace_EPFMI_vMmiDoAction,
   TT_EPFMI_vMmiDoAction2                       = SHMEM_nenTrace_EPFMI_vMmiDoAction2,
   TT_CUH_vRegisterAppForKeys                   = SHMEM_nenTrace_CUH_vRegisterAppForKeys,
   TT_CUH_vDeRegisterAppForKeys                 = SHMEM_nenTrace_CUH_vDeRegisterAppForKeys,
   TT_vWAS_KeyFilterDoEventProcessing           = SHMEM_nenTrace_vWAS_KeyFilterDoEventProcessing,
   TT_vActivateFilter                           = SHMEM_nenTrace_vActivateFilter,
   TT_vGetLastMessages                          = SHMEM_nenTrace_vGetLastMessages,
   TT_Filter_vActivate                          = SHMEM_nenTrace_Filter_vActivate,
   TT_KeyFilter_operator                        = SHMEM_nenTrace_KeyFilter_operator,
   TT_vRun_Msg                                  = SHMEM_nenTrace_vRun_Msg,
   TT_WPAStoryBoard_vSetActive                  = SHMEM_nenTrace_WPAStoryBoard_vSetActive,
   TT_WPAAnimationStartedOutEvent               = SHMEM_nenTrace_WPAAnimationStartedOutEvent,
   TT_StoryBoardDeactivated                     = SHMEM_nenTrace_StoryBoardDeactivated,
   TT_WPAAnimationFinishedOutEvent              = SHMEM_nenTrace_WPAAnimationFinishedOutEvent,
   TT_WPAStoryBoard_vTimeTick                   = SHMEM_nenTrace_WPAStoryBoard_vTimeTick,
   TT_WPAAnimationStarted                       = SHMEM_nenTrace_WPAAnimationStarted,
   TT_WPAAnimationStopped                       = SHMEM_nenTrace_WPAAnimationStopped,
   TT_WPAAnimationDestroyNotifcation            = SHMEM_nenTrace_WPAAnimationDestroyNotifcation,
   TT_SelfWidgetBase_vOnAnimActive              = SHMEM_nenTrace_SelfWidgetBase_vOnAnimActive,
   TT_WPASBSelf_enProcessMessage                = SHMEM_nenTrace_WPASBSelf_enProcessMessage,
   TT_WPASBSelf_vUpdateAnimParamsInvert         = SHMEM_nenTrace_WPASBSelf_vUpdateAnimParamsInvert,
   TT_WPASBSelf_vTimeTick                       = SHMEM_nenTrace_WPASBSelf_vTimeTick,
   TT_WPASBSelf_vSetActive                      = SHMEM_nenTrace_WPASBSelf_vSetActive,
   TT_WPASBSelf_vStoreStaticValue               = SHMEM_nenTrace_WPASBSelf_vStoreStaticValue,
   TT_WPAESSelf_vStoreStaticValue               = SHMEM_nenTrace_WPAESSelf_vStoreStaticValue,
   TT_WPASBSelf_vRestoreModelValue              = SHMEM_nenTrace_WPASBSelf_vRestoreModelValue,
   TT_WPAESSelf_vRestoreModelValue              = SHMEM_nenTrace_WPAESSelf_vRestoreModelValue,
   TT_WPASBSelf_vRequestUpdateAnimParams        = SHMEM_nenTrace_WPASBSelf_vRequestUpdateAnimParams,
   TT_WPASBSelf_vUpdateAnimParamsSelf           = SHMEM_nenTrace_WPASBSelf_vUpdateAnimParamsSelf,
   TT_WPASBSelf_vUpdateAnimParamsSelfRuntime    = SHMEM_nenTrace_WPASBSelf_vUpdateAnimParamsSelfRuntime,
   TT_UpdateEasingForAllScenes                  = SHMEM_nenTrace_UpdateEasingForAllScenes,
   TT_UpdateDuration                            = SHMEM_nenTrace_UpdateDuration,
   TT_UpdateAnimation                           = SHMEM_nenTrace_UpdateAnimation,
   TT_m_vOnLongPressInit                        = SHMEM_nenTrace_m_vOnLongPressInit,
   TT_LongPressStarted                          = SHMEM_nenTrace_LongPressStarted,
   TT_m_vOnLongPressRetrigger                   = SHMEM_nenTrace_m_vOnLongPressRetrigger,
   TT_m_vOnLongPressReleased                    = SHMEM_nenTrace_m_vOnLongPressReleased,
   TT_Anima_vPropagateAnimData                  = SHMEM_nenTrace_Anima_vPropagateAnimData,
   TT_Anima_vSetActiveAnimData                  = SHMEM_nenTrace_Anima_vSetActiveAnimData,
   TT_Anima_vSetWaitingAnimData                 = SHMEM_nenTrace_Anima_vSetWaitingAnimData,
   TT_Anima_vSetTimeTickDirection               = SHMEM_nenTrace_Anima_vSetTimeTickDirection,
   TT_Anima_vOnPreLayoutingHook                 = SHMEM_nenTrace_Anima_vOnPreLayoutingHook,
   TT_SMG_vControllerSync                       = SHMEM_nenTrace_SMG_vControllerSync,
   TT_SMG_vInitActive15                         = SHMEM_nenTrace_SMG_vInitActive15,
   TT_SMG_vDeinitActive15                       = SHMEM_nenTrace_SMG_vDeinitActive15,
   TT_SMG_vInitHoldDisplay                      = SHMEM_nenTrace_SMG_vInitHoldDisplay,
   TT_SMG_vDeinitHoldDisplay                    = SHMEM_nenTrace_SMG_vDeinitHoldDisplay,
   TT_SMG_vDoEventProcessing                    = SHMEM_nenTrace_SMG_vDoEventProcessing,
   TT_ILU_vInitActiveDisplay                    = SHMEM_nenTrace_ILU_vInitActiveDisplay,
   TT_ILU_vDeinitActiveDisplay                  = SHMEM_nenTrace_ILU_vDeinitActiveDisplay,
   TT_ILU_vCPrePostRunDeinit15                  = SHMEM_nenTrace_ILU_vCPrePostRunDeinit15,
   TT_ILU_vCPrePostRunDoEventProcessing         = SHMEM_nenTrace_ILU_vCPrePostRunDoEventProcessing,
   TT_SetReq_HoldDisplayByIluDisplayUsed        = SHMEM_nenTrace_SetReq_HoldDisplayByIluDisplayUsed,
   TT_ClearReq_HoldDisplayByIluDisplayUsed      = SHMEM_nenTrace_ClearReq_HoldDisplayByIluDisplayUsed,
   TT_SetReq_Active15BySMGIgnition              = SHMEM_nenTrace_SetReq_Active15BySMGIgnition,
   TT_ClearReq_Active15BySMG                    = SHMEM_nenTrace_ClearReq_Active15BySMG,
   TT_SetReq_HoldDisplayBySMG                   = SHMEM_nenTrace_SetReq_HoldDisplayBySMG,
   TT_ClearReq_HoldDisplayBySMG                 = SHMEM_nenTrace_ClearReq_HoldDisplayBySMG,
   TT_SetReq_ActiveDisplayBySMG                 = SHMEM_nenTrace_SetReq_ActiveDisplayBySMG,
   TT_ClearReq_ActiveDisplayBySMG               = SHMEM_nenTrace_ClearReq_ActiveDisplayBySMG,
   TT_TIMER_vStart_nIluPrePostRunTimer          = SHMEM_nenTrace_TIMER_vStart_nIluPrePostRunTimer,
   TT_TIMER_vStart_nActiveDisplayTimeout        = SHMEM_nenTrace_TIMER_vStart_nActiveDisplayTimeout,
   TT_srStateHMI_Inactive__ENV_InitEvent        = SHMEM_nenTrace_srStateHMI_Inactive__ENV_InitEvent,
   TT_srStateHMI_Reset__FW_InitEvent            = SHMEM_nenTrace_srStateHMI_Reset__FW_InitEvent,
   TT_srStateHMI_Reset__ENV_DeinitEvent         = SHMEM_nenTrace_srStateHMI_Reset__ENV_DeinitEvent,
   TT_srStateHMI_Active__FW_DeinitEvent         = SHMEM_nenTrace_srStateHMI_Active__FW_DeinitEvent,  
   TT_HMI_vReset                                = SHMEM_nenTrace_HMI_vReset,
   TT_HMI_vWakeup                               = SHMEM_nenTrace_HMI_vWakeup,
   TT_HMI_vSleep                                = SHMEM_nenTrace_HMI_vSleep,
   TT_HMI_vDisplayOn                            = SHMEM_nenTrace_HMI_vDisplayOn,
   TT_HMI_vDisplayOff                           = SHMEM_nenTrace_HMI_vDisplayOff,
   TT_HMI_vSyncInit                             = SHMEM_nenTrace_HMI_vSyncInit,
   TT_HMI_vAsyncDeInit                          = SHMEM_nenTrace_HMI_vAsyncDeInit,
   TT_HMI_boSetDependency                       = SHMEM_nenTrace_HMI_boSetDependency,
   TT_APIM_vInitialization                      = SHMEM_nenTrace_APIM_vInitialization,
   TT_APIM_vDeinitialization                    = SHMEM_nenTrace_APIM_vDeinitialization,
   TT_APIM_Reset                                = SHMEM_nenTrace_APIM_Reset,
   TT_APIM_boSetData                            = SHMEM_nenTrace_APIM_boSetData,
// TT_APIM_boGetData                            = SHMEM_nenTrace_APIM_boGetData,
   TT_APIM_boGetData__APIM_nDId_ai32DP_SINT     = SHMEM_nenTrace_APIM_boGetData__APIM_nDId_ai32DP_SINT,
   TT_APIM_boGetData__APIM_nDId_aboDP_BOOL      = SHMEM_nenTrace_APIM_boGetData__APIM_nDId_aboDP_BOOL,
   TT_WMMS_u8Init                               = SHMEM_nenTrace_WMMS_u8Init,
   TT_WMMS_u8DeInit                             = SHMEM_nenTrace_WMMS_u8DeInit,
   TT_boSendSignalWithoutData                   = SHMEM_nenTrace_boSendSignalWithoutData,
   TT_transit_CSHStateHMI_Reset                 = SHMEM_nenTrace_transit_CSHStateHMI_Reset,
   TT_transit_CSHStateHMI_Active                = SHMEM_nenTrace_transit_CSHStateHMI_Active,
   TT_transit_CSHStateHMI_Inactive              = SHMEM_nenTrace_transit_CSHStateHMI_Inactive,
   TT_API_Pool__vInitResources                  = SHMEM_nenTrace_API_Pool__vInitResources,
   TT_API_Pool__vDeInitResources                = SHMEM_nenTrace_API_Pool__vDeInitResources,
   TT_API_Timer_vInitResource                   = SHMEM_nenTrace_API_Timer_vInitResource,
   TT_API_Timer_vDeInitResource                 = SHMEM_nenTrace_API_Timer_vDeInitResource,
   TT_WRM_u8Request                             = SHMEM_nenTrace_WRM_u8Request,
   TT_WRM__vCASendWarningNotification           = SHMEM_nenTrace_WRM__vCASendWarningNotification,
   TT_WRA_ActivateZWL                           = SHMEM_nenTrace_WRA_ActivateZWL,
   TT_boSignalSI__InitRES_HMI_Framwork_ANY      = SHMEM_nenTrace_boSignalSI__InitRES_HMI_Framwork_ANY,
   TT_boSignalSI__DeinitRES_HMI_Framwork_ANY    = SHMEM_nenTrace_boSignalSI__DeinitRES_HMI_Framwork_ANY,
   TT_CRHDL_enStateHdlGetState0                 = SHMEM_nenTrace_CRHDL_enStateHdlGetState0,
   TT_CRHDL_enStateHdlGetState1                 = SHMEM_nenTrace_CRHDL_enStateHdlGetState1,
   TT_boSignalSI_EV_DiagAdaption_0_Change       = SHMEM_nenTrace_boSignalSI_EV_DiagAdaption_0_Change,
   TT_boSignalSI_EV_DiagCodingChange            = SHMEM_nenTrace_boSignalSI_EV_DiagCodingChange,
   TT_boSignalSI_EV_DPOOL_OnChange_M_Language   = SHMEM_nenTrace_boSignalSI_EV_DPOOL_OnChange_M_Language,
   TT_GetDPOOL_M_Language                       = SHMEM_nenTrace_GetDPOOL_M_Language,
   TT_MFARoleContainer_enProcessMessage         = SHMEM_nenTrace_MFARoleContainer_enProcessMessage,
   TT_MFARoleContainer_vProcessKey              = SHMEM_nenTrace_MFARoleContainer_vProcessKey,
   TT_SelfWidgetBase_m_vOnKeyPressed            = SHMEM_nenTrace_SelfWidgetBase_m_vOnKeyPressed,
   TT_SelfSSMCoreCommon_m_vOnKeyPressed         = SHMEM_nenTrace_SelfSSMCoreCommon_m_vOnKeyPressed,
   TT_SelfWidgetMFA_boHandleKey                 = SHMEM_nenTrace_SelfWidgetMFA_boHandleKey,
   TT_SelfWidgetList_boHandleKey                = SHMEM_nenTrace_SelfWidgetList_boHandleKey,
   TT_Framework_TriggerForcedPaint              = SHMEM_nenTrace_Framework_TriggerForcedPaint,
   TT_SelfSSMCoreCommon_vUpdateMC               = SHMEM_nenTrace_SelfSSMCoreCommon_vUpdateMC,
   TT_SelfWidgetWPABase_vUpdateAnimation        = SHMEM_nenTrace_SelfWidgetWPABase_vUpdateAnimation,
   TT_SelfWidgetBase_vUpdateStateSSMCore        = SHMEM_nenTrace_SelfWidgetBase_vUpdateStateSSMCore,
   TT_SelfWidgetBase_stSetAnimData              = SHMEM_nenTrace_SelfWidgetBase_stSetAnimData,
   TT_SelfWidgetBase_stGetAnimData              = SHMEM_nenTrace_SelfWidgetBase_stGetAnimData,
   TT_SelfWidgetBase_vOnElapsed                 = SHMEM_nenTrace_SelfWidgetBase_vOnElapsed,
   TT_SelfSSMCoreCommon_vOnElapsed              = SHMEM_nenTrace_SelfSSMCoreCommon_vOnElapsed,
   TT_SelfSSMMoveCounter_vOnElapsed             = SHMEM_nenTrace_SelfSSMMoveCounter_vOnElapsed,
   TT_vOnMFAIterationAnimationDone              = SHMEM_nenTrace_vOnMFAIterationAnimationDone,
   TT_SelfWidgetBase_boHandleKeySSMCore         = SHMEM_nenTrace_SelfWidgetBase_boHandleKeySSMCore,
   TT_vPropagateAnimDataActiveAnim              = SHMEM_nenTrace_vPropagateAnimDataActiveAnim,
   TT_vPropagateAnimDataWaitingAnim             = SHMEM_nenTrace_vPropagateAnimDataWaitingAnim,
   TT_vSetUpdateFreezeModeInLastBeforeDraw      = SHMEM_nenTrace_vSetUpdateFreezeModeInLastBeforeDraw,
   TT_m_vOnLPInit                               = SHMEM_nenTrace_m_vOnLPInit,
   TT_m_vActivateLPMode                         = SHMEM_nenTrace_m_vActivateLPMode,
   TT_m_vOnLPRetrigger                          = SHMEM_nenTrace_m_vOnLPRetrigger,
   TT_m_vOnLPRelease                            = SHMEM_nenTrace_m_vOnLPRelease,
   TT_m_vOnViewChange                           = SHMEM_nenTrace_m_vOnViewChange,
   TT_m_vFlush                                  = SHMEM_nenTrace_m_vFlush,
   TT_ControlAC_enProcessMessage                = SHMEM_nenTrace_ControlAC_enProcessMessage,
   TT_Messenger_vProcessMessage                 = SHMEM_nenTrace_Messenger_vProcessMessage,
   TT_SelfSSMCoreCommon_vProcessElapsed         = SHMEM_nenTrace_SelfSSMCoreCommon_vProcessElapsed,
   TT_ListAnimationVwFPK_enProcessMessage       = SHMEM_nenTrace_ListAnimationVwFPK_enProcessMessage,
   TT_SelfSSMCoreCommon_m_vRunStateMachine      = SHMEM_nenTrace_SelfSSMCoreCommon_m_vRunStateMachine,
   TT_KeyHandlerMaster_vInit                    = SHMEM_nenTrace_KeyHandlerMaster_vInit,
   TT_KeyHandlerMaster_vDeinit                  = SHMEM_nenTrace_KeyHandlerMaster_vDeinit,
   TT_HMI_boSendMessage                         = SHMEM_nenTrace_HMI_boSendMessage,
   TT_WIDVWFPK_vInitGlobalData                  = SHMEM_nenTrace_WIDVWFPK_vInitGlobalData,
   TT_UTILS_vInitGlobalData                     = SHMEM_nenTrace_UTILS_vInitGlobalData,
   TT_PAINTER_vInitGlobalData                   = SHMEM_nenTrace_PAINTER_vInitGlobalData,
   TT_HMItimedomain_vRun                        = SHMEM_nenTrace_HMItimedomain_vRun,
   TT_APIM_Lock                                 = SHMEM_nenTrace_APIM_Lock,
   TT_APIM_pstGetClientHook                     = SHMEM_nenTrace_APIM_pstGetClientHook,
   TT_APIM_HMI_Lock_Pre                         = SHMEM_nenTrace_APIM_HMI_Lock_Pre,
   TT_MOSTA_vPullPictureBuffer                  = SHMEM_nenTrace_MOSTA_vPullPictureBuffer,
   TT_APIM_HMI_Lock_Post                        = SHMEM_nenTrace_APIM_HMI_Lock_Post,
   TT_VSF_vHandleWarningDetailsRequests         = SHMEM_nenTrace_VSF_vHandleWarningDetailsRequests,
   TT_VSF_vHandleWarningNumberOfLinesRequests   = SHMEM_nenTrace_VSF_vHandleWarningNumberOfLinesRequests,
   TT_VSF_vCheckAPIChanges                      = SHMEM_nenTrace_VSF_vCheckAPIChanges,
   TT_CarouselContainer_enProcessMessage        = SHMEM_nenTrace_CarouselContainer_enProcessMessage,
   TT_SelfMainMenuRoll_boHandleKey              = SHMEM_nenTrace_SelfMainMenuRoll_boHandleKey,
   TT_m_vSetFreezeMode                          = SHMEM_nenTrace_m_vSetFreezeMode,
   TT_KeyHandlerMaster_vUnfreeze                = SHMEM_nenTrace_KeyHandlerMaster_vUnfreeze,
   TT_vUpdateWaitingAnimation                   = SHMEM_nenTrace_vUpdateWaitingAnimation,
   TT_vOnMsgAddedToKeyQueue                     = SHMEM_nenTrace_vOnMsgAddedToKeyQueue,
   TT_u8AddNewKeys                              = SHMEM_nenTrace_u8AddNewKeys,
   TT_m_boNeutralizeNewKeysVirtualKeys          = SHMEM_nenTrace_m_boNeutralizeNewKeysVirtualKeys,
   TT_boInvert                                  = SHMEM_nenTrace_boInvert,
   TT_vOnLastBeforeDraw                         = SHMEM_nenTrace_vOnLastBeforeDraw,
   TT_SelfMainMenuRoll_tCreateAnimation         = SHMEM_nenTrace_SelfMainMenuRoll_tCreateAnimation,
   TT_KeyHandlerMaster_vFreeze                  = SHMEM_nenTrace_KeyHandlerMaster_vFreeze,
   TT_vActivateStaticModeViewSkipping           = SHMEM_nenTrace_vActivateStaticModeViewSkipping,
   TT_m_vRetryKeyProcessing                     = SHMEM_nenTrace_m_vRetryKeyProcessing,
   TT_m_vOnViewChangeFlushKeyQueue              = SHMEM_nenTrace_m_vOnViewChangeFlushKeyQueue,
   TT_vFlushToSystemMsgQueue                    = SHMEM_nenTrace_vFlushToSystemMsgQueue,
   TT_KeyHandlerMaster_vDeactivate              = SHMEM_nenTrace_KeyHandlerMaster_vDeactivate,
   TT_vDiscardAllMessages                       = SHMEM_nenTrace_vDiscardAllMessages,
   TT_m_vRemoveAllVirtualKeysFromSSM            = SHMEM_nenTrace_m_vRemoveAllVirtualKeysFromSSM,
   TT_m_vOnViewChangeDiscardKeyQueue            = SHMEM_nenTrace_m_vOnViewChangeDiscardKeyQueue,
   TT_boGetCfgDeactivateKHAtUnfreeze            = SHMEM_nenTrace_boGetCfgDeactivateKHAtUnfreeze,
   TT_KeyHandlerMaster_vActivate                = SHMEM_nenTrace_KeyHandlerMaster_vActivate,
   TT_KeyHandlerMaster_boAddMessage             = SHMEM_nenTrace_KeyHandlerMaster_boAddMessage,
   TT_WarningState_enProcessMessage             = SHMEM_nenTrace_WarningState_enProcessMessage,
   TT_SelfWidgetWarningState_boHandleKey        = SHMEM_nenTrace_SelfWidgetWarningState_boHandleKey,
   TT_ScrollBar_enProcessMessage                = SHMEM_nenTrace_ScrollBar_enProcessMessage,
   TT_SelfOwnerPopupInvert_enProcessMessage     = SHMEM_nenTrace_SelfOwnerPopupInvert_enProcessMessage,
   TT_SelfPopupInvert_boHandleKey               = SHMEM_nenTrace_SelfPopupInvert_boHandleKey,
   TT_boDisableInversion                        = SHMEM_nenTrace_boDisableInversion,
   TT_CarouselContainer_start_timer             = SHMEM_nenTrace_CarouselContainer_start_timer,
   TT_LayoutController_enProcessMessage         = SHMEM_nenTrace_LayoutController_enProcessMessage,
   TT_SelfLayout_boHandleKey                    = SHMEM_nenTrace_SelfLayout_boHandleKey,
   TT_WDOG_vEnableEntity                        = SHMEM_nenTrace_WDOG_vEnableEntity,
   TT_WDOG_vDisableEntity                       = SHMEM_nenTrace_WDOG_vDisableEntity,
   TT_WDOG_vUpdateEntitiesList                  = SHMEM_nenTrace_WDOG_vUpdateEntitiesList,
   TT_DispatchEvent                             = SHMEM_nenTrace_DispatchEvent,
   TT_Display_vOnLastBeforeDeactivation         = SHMEM_nenTrace_Display_vOnLastBeforeDeactivation,
   TT_AVICORE_vTaskDeactivationCallback         = SHMEM_nenTrace_AVICORE_vTaskDeactivationCallback,
   TT_GRLC_vDisconnectSurfaceID                 = SHMEM_nenTrace_GRLC_vDisconnectSurfaceID,
   TT_GRLC_vSurfaceDelete                       = SHMEM_nenTrace_GRLC_vSurfaceDelete,
   TT_GRLC_vLayerDelete                         = SHMEM_nenTrace_GRLC_vLayerDelete,
   TT_Display_vOnTaskActivated                  = SHMEM_nenTrace_Display_vOnTaskActivated,
   TT_GRLC_vVideoOutSetLayerUpdateMode          = SHMEM_nenTrace_GRLC_vVideoOutSetLayerUpdateMode,
   TT_AVICORE_vTaskActivationCallback           = SHMEM_nenTrace_AVICORE_vTaskActivationCallback,
   TT_GRLC_u16LayerCreate                       = SHMEM_nenTrace_GRLC_u16LayerCreate,
   TT_GRLC_u16SurfaceCreate                     = SHMEM_nenTrace_GRLC_u16SurfaceCreate,
   TT_GRLC_vConnectSurfaceID                    = SHMEM_nenTrace_GRLC_vConnectSurfaceID,
   TT_GRLC_vLayerSetVisibility                  = SHMEM_nenTrace_GRLC_vLayerSetVisibility,
   TT_GRLC_vLayerSetPerPixelTransparency        = SHMEM_nenTrace_GRLC_vLayerSetPerPixelTransparency,
   TT_EEH_u8GetPixelOffset                      = SHMEM_nenTrace_EEH_u8GetPixelOffset,
   TT_EEH_i8Getp_Verschiebung_Displayinhalte    = SHMEM_nenTrace_EEH_i8Getp_Verschiebung_Displayinhalte,
   TT_GRLC_vDisplaySetOffset                    = SHMEM_nenTrace_GRLC_vDisplaySetOffset,
   TT_VCAnimationCreated                        = SHMEM_nenTrace_VCAnimationCreated,
   TT_VCAnimationStarted                        = SHMEM_nenTrace_VCAnimationStarted,
   TT_VCAnimationStopped                        = SHMEM_nenTrace_VCAnimationStopped,

} TT_tenEventIds;

typedef enum
{
    TT_HMIQueueLoad              = SHMEM_nenTrace_HMIQueueLoad,
    TT_SetDPOOL                  = SHMEM_nenTrace_SetDPOOL,
    TT_GetDPOOL                  = SHMEM_nenTrace_GetDPOOL,
    TT_SelfState_OLD             = SHMEM_nenTrace_SelfState_OLD,
    TT_SelfState                 = SHMEM_nenTrace_SelfState,
    TT_MoveCounter               = SHMEM_nenTrace_MoveCounter,
    TT_HmiFrameId                = SHMEM_nenTrace_HmiFrameId,
} TT_tenDataIds;

typedef enum
{
} TT_tenObjectType;

typedef enum
{
    TT_HMI_stExtQFillLevel,
    TT_SMG_T15_Status,
    TT_EPFMI_boModelKeyDisplaced,
    TT_hmi_skin_download_byGraBoot,
    TT_M_Language,
} TT_tenDPoolNameType;

void TT_vTraceFormat(const char *pcFormat, ...);
void TT_vTraceEvent(TT_tenEventIds enEvent, ...);
void TT_vTraceData(TT_tenDataIds enData, ...);
void TT_vPatchObject(void *pvObject, TT_tenObjectType enType);
void TT_vSystemEvent(uint32 ev);

extern uint32 TT_storedHmiFrameId;

#ifndef _PC_SIMULATION_
#define TT_vTraceFormat(a,...)
#define TT_vTraceEvent(a,...)
#define TT_vTraceData(a,...)
#define TT_vPatchObject(a,b)

#endif


#endif
